modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "viscord"
version = "${version}"
displayName = "Viscord"
authors = "Vonix"
description = '''
Discord Multi-Server Integration for Minecraft - Optimized for multiple servers with embed parsing and anti-loop for webhooks
'''
#logoFile = ""

[[dependencies.viscord]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscord]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscord]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
